language: elixir
elixir: '1.10'
otp_release: '22.2'

before_install:
- mix local.hex --force
- mix local.rebar --force
- mix deps.get
- mix compile

script:
- mix routekut.create
- tar cfz linux-ipv4.tar.gz add_rotues.sh db

deploy:
  provider: releases
  api_key:
    secure: "XWvoCenWkZ2uTviOTzztP8b+CoWzS1VtZd5gHcRd9v9WadkixbT9aCMY86WAWLfXnr5MbibSy1qT40Jx+YjsEeDLznAd04qXSFLfiuw/8J+Y9MAl98IapQQ7BRa8mTNELH744iwDWA5XesHqMfTttvV8d057me1BoFnX0UgFlF4CHu4N8XXKDdvIKY3Zao1gcnuOWSK6/styOqBRAFRBcCUlK4LOfAvXnw0Lav9MLuTXbK549NgC1K5nJRLC8XhD2TNjOK6jBguuHT6JcplcScMKsJdpHjU6eQMvdulkTuxRikbnZahnCY8oxQVojcCneVMJlxINBKrIXqwxjcdTb9AYlMZr4PipIbxBO1a6YMoP7Re9oI4GfDsyiQWgcFAZZ0zPOEdyvZEAGg7MTtOcUzCnYNzex6wxGiYu246EkDzoT7JpA3otx1QuIOjBs68xhv9U7ckdBeFFw8jxaWBehZSDDv9pS6zGwLFWfdTsaSbh2XyJmrwUwp0+z+82DVLDsmdrqOv3Wbe389q4WV2GgZdatJ/8PsOlV1s0+WH2keiFK2ueK4idSIG21Km6pV+g51J/ilZoqO8v7PMOQ4LoXeXNeEnbDArdgEhHwcCKc3gykkUZgKJXH08+qhjFVf1QKuHFL4EA5yQvUqvMUcCSk16vprm5ZvNqHH89h+sHMN4="
  file: "linux-ipv4.tar.gz"
  skip_cleanup: true
  on:
    tags: true
